### ISSUE TITLE
Pass doesn't update

### ISSUE THREAD

**Issue by JaapWijnen** [ole/Kaffeekasse#2]
Hi I'm trying to follow the instructions on your blog post, but my pass doesn't update when I change the value on the webpage. Also I'm having trouble connecting from my iphone to my macbook's .local domain. Currently I just use the iPhone simulator and go to localhost:4567. Any ideas?

**Comment by ole** [comment]
This code is so old that I wouldn't be surprised if something broke in the meantime, but I currently neither have the time nor the inclination to investigate this further.

**Comment by JaapWijnen** [comment]
Ok thanks for the response! Already was afraid that would be the case ;)
